# Generated by Django 5.2.5 on 2025-10-24 02:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feetype',
            options={'ordering': ['name']},
        ),
        migrations.AlterUniqueTogether(
            name='feetype',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='feetype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feetype',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.RemoveField(
            model_name='feetype',
            name='default_amount',
        ),
        migrations.RemoveField(
            model_name='feetype',
            name='level',
        ),
        migrations.CreateModel(
            name='FeeTypeAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('fee_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amounts', to='fees.feetype')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_type_amounts', to='academics.level')),
            ],
            options={
                'ordering': ['level__id', 'fee_type__name'],
                'unique_together': {('fee_type', 'level')},
            },
        ),
    ]
