# Generated by Django 5.2.5 on 2025-11-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_alter_feetype_options_alter_feetype_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feetype',
            name='due_date',
            field=models.DateField(blank=True, help_text='Date limite par défaut pour ce type de frais (peut être surchargée au niveau du Fee).', null=True),
        ),
    ]
