# Generated by Django 5.2.5 on 2025-10-23 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classscheduleentry',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='timetable_entries', to='core.teacher'),
        ),
        migrations.AddField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='core.student'),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='academics.level'),
        ),
        migrations.AddField(
            model_name='classsubject',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='academics.schoolclass'),
        ),
        migrations.AddField(
            model_name='classscheduleentry',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable', to='academics.schoolclass'),
        ),
        migrations.AddField(
            model_name='grade',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='classsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='classscheduleentry',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timetable_entries', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='subjectcomment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_comments', to='core.student'),
        ),
        migrations.AddField(
            model_name='subjectcomment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_comments', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='subjectcomment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_comments', to='core.teacher'),
        ),
        migrations.AlterUniqueTogether(
            name='schoolclass',
            unique_together={('name', 'level')},
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('student', 'subject', 'term')},
        ),
        migrations.AlterUniqueTogether(
            name='classsubject',
            unique_together={('school_class', 'subject')},
        ),
        migrations.AlterUniqueTogether(
            name='subjectcomment',
            unique_together={('student', 'subject', 'term')},
        ),
    ]
