# Generated by Django 5.2.5 on 2025-12-01 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_announcement'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('ABSENT', 'Absent'), ('LATE', 'Retard'), ('EXCUSED', 'Excusé')], default='ABSENT', max_length=10)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('schedule_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_attendances', to='academics.classscheduleentry')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='core.student')),
            ],
            options={
                'indexes': [models.Index(fields=['date', 'schedule_entry'], name='academics_s_date_b2ce35_idx')],
                'unique_together': {('student', 'schedule_entry', 'date')},
            },
        ),
    ]
