# Generated by Django 5.2.5 on 2026-02-23 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_studentattendance'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('T1', '1er trimestre'), ('T2', '2e trimestre'), ('T3', '3e trimestre')], max_length=10)),
                ('interrogation1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('interrogation2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('interrogation3', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('devoir1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('devoir2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_grades', to='core.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_grades', to='academics.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_grades', to='core.teacher')),
            ],
            options={
                'ordering': ['teacher__user__username', 'student__user__username', 'subject__name'],
                'unique_together': {('teacher', 'student', 'subject', 'term')},
            },
        ),
    ]
