# Generated by Django 5.2.5 on 2026-03-08 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_attendancesession_alter_studentattendance_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolYearConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_terms', models.PositiveSmallIntegerField(choices=[(2, '2 trimestres'), (3, '3 trimestres')], default=3, help_text="Nombre de trimestres pour toute l'école (2 ou 3).")),
                ('current_year', models.CharField(default='2024-2025', help_text='Année scolaire en cours. Exemple : 2024-2025.', max_length=9)),
            ],
            options={
                'verbose_name': "Configuration de l'année scolaire",
            },
        ),
        migrations.CreateModel(
            name='TermStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Brouillon (saisie ouverte)'), ('locked', 'Verrouillé (moyennes calculées)'), ('published', 'Publié (visible aux élèves)')], db_index=True, default='draft', max_length=20)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_terms', to=settings.AUTH_USER_MODEL)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_statuses', to='academics.schoolclass')),
            ],
            options={
                'ordering': ['school_class__name', 'term'],
                'unique_together': {('school_class', 'term')},
            },
        ),
        migrations.CreateModel(
            name='TermSubjectConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=10)),
                ('nb_interros', models.PositiveSmallIntegerField(default=3, help_text="Nombre d'interrogations prévues (1, 2 ou 3). Sert de diviseur fixe.")),
                ('nb_devoirs', models.PositiveSmallIntegerField(default=2, help_text='Nombre de devoirs prévus (0, 1 ou 2).')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_subject_configs', to='academics.schoolclass')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_subject_configs', to='academics.subject')),
            ],
            options={
                'ordering': ['school_class__name', 'subject__name', 'term'],
                'unique_together': {('school_class', 'subject', 'term')},
            },
        ),
    ]
