# Generated by Django 5.2.5 on 2025-11-18 17:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=120, unique=True)),
                ('topic', models.CharField(choices=[('fees', 'Frais'), ('grades', 'Notes'), ('bulletin', 'Bulletin'), ('attendance', 'Absences'), ('message', 'Messagerie'), ('timetable', 'Emploi du temps')], max_length=50)),
                ('title_template', models.CharField(max_length=200)),
                ('body_template', models.TextField()),
                ('default_channels', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic', models.CharField(choices=[('fees', 'Frais'), ('grades', 'Notes'), ('bulletin', 'Bulletin'), ('attendance', 'Absences'), ('message', 'Messagerie'), ('timetable', 'Emploi du temps')], max_length=50)),
                ('payload', models.JSONField(default=dict)),
                ('channels', models.JSONField(default=list)),
                ('sent', models.BooleanField(default=False)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('recipient_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.notificationtemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('inapp', 'In-App'), ('email', 'Email'), ('sms', 'SMS'), ('push', 'Push')], max_length=20)),
                ('tried_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=False)),
                ('response', models.TextField(blank=True, null=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='notifications.notification')),
            ],
        ),
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='fcm', max_length=30)),
                ('token', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserNotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(choices=[('fees', 'Frais'), ('grades', 'Notes'), ('bulletin', 'Bulletin'), ('attendance', 'Absences'), ('message', 'Messagerie'), ('timetable', 'Emploi du temps')], max_length=50)),
                ('channels', models.JSONField(default=list)),
                ('enabled', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient_user', 'created_at'], name='notificatio_recipie_a86600_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['topic', 'created_at'], name='notificatio_topic_df9e74_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usernotificationpreference',
            unique_together={('user', 'topic')},
        ),
    ]
